//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALCOMPRA
    {
        public int IDHISTORIALCOMPRA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDPRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIOTOTAL { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
