//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSCRIPCIONE
    {
        public int IDSUSCRIPCIÓN { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDMEMBRESIA { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEMBRESiA MEMBRESiA { get; set; }
    }
}
